### ISSUE TITLE
npm install error - shop.js

### ISSUE THREAD

**Issue by Zaekof** [shopjs/shop.js#232]
# Hi!

### i'am block on a error at install and my log's tell me that :
-> verbose type version
-> verbose stack el-controls: No matching version found for el-controls@1.2.35

### info :
 node v8.9.4
 npm  v5.6.0

Thanks.

**Comment by zeekay** [comment]
Rolled back el-controls version. We have a new version coming out soon! Sorry about that.

**Comment by Zaekof** [comment]
Hi,

Ok thanks.
